title: elcebr
description: >
  a dude who likes reverse, exploit development, ai furthermore PHYSICS
permalink: ':title/'
baseurl: "/"
url: "https://elcebr.github.io" 
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Utku Çorbacı 
author-img: utku.png # add your photo
about-author: a dude who likes reverse, exploit development, ai
social-twitter: elcebr
social-facebook:
social-github: elcebr
social-linkedin:
social-email: corbaciutku@gmail.com

# Disqus
discus-identifier:  

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
